name: Fork Auto-Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

permissions:
  contents: write

jobs:
  sync:
    if: github.repository != 'kuestcom/prediction-market'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Configure git author/committer
        run: |
          git config user.name  "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

      - name: Sync with upstream
        run: |
          git remote get-url upstream || git remote add upstream https://github.com/kuestcom/prediction-market.git
          git fetch upstream
          UPSTREAM_HASH=$(git rev-parse upstream/main)
          LOCAL_HASH=$(git rev-parse HEAD)
          if [ "$UPSTREAM_HASH" = "$LOCAL_HASH" ]; then
            echo "Already synced with upstream. Skipping."
            exit 0
          fi
          echo "Syncing with upstream..."
          LATEST_COMMIT_MSG=$(git log upstream/main -1 --pretty=format:"%s")
          git reset --hard upstream/main
          git push --force origin main
